# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator_', '0003_auto_20181123_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrage2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
            ],
        ),
    ]
