# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-20 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityID', models.IntegerField(default=0)),
                ('IDs', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('First', models.IntegerField(default=0)),
                ('Second', models.IntegerField(default=0)),
                ('Third', models.IntegerField(default=0)),
                ('Special', models.IntegerField(default=0)),
                ('Statue', models.CharField(max_length=20)),
            ],
        ),
    ]
