# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-23 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityID', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=30)),
                ('Organnizer', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('PirUrl', models.CharField(max_length=100)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('BgPicUrl', models.CharField(max_length=100)),
                ('Statue', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Barrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
            ],
        ),
    ]
