# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-23 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator_', '0002_activity_barrage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='BgPicUrl',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='PirUrl',
            field=models.ImageField(upload_to=''),
        ),
    ]
