# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-19 17:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('pic_url', models.ImageField(max_length=255, upload_to='')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 12, 19, 17, 54, 8, 728145, tzinfo=utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2018, 12, 19, 17, 54, 8, 728145, tzinfo=utc))),
                ('bg_pic_url', models.ImageField(max_length=255, upload_to='')),
                ('status', models.IntegerField()),
                ('sign', models.IntegerField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 12, 19, 17, 54, 8, 729145, tzinfo=utc))),
                ('content', models.CharField(max_length=100)),
                ('color', models.IntegerField()),
                ('bolt', models.BooleanField()),
                ('underline', models.BooleanField()),
                ('incline', models.BooleanField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.Activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('third', models.IntegerField()),
                ('special', models.IntegerField()),
                ('status', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.Lottery')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_id', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 12, 19, 17, 54, 8, 729145, tzinfo=utc))),
                ('pic_url', models.ImageField(max_length=255, upload_to='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.Activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=300)),
                ('sequence', models.IntegerField()),
                ('actors', models.CharField(default='', max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject.Activity')),
            ],
        ),
    ]
