# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-22 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 8, 49, 43, 985534, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 8, 49, 43, 985534, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 8, 49, 43, 986531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 8, 49, 43, 986531, tzinfo=utc)),
        ),
    ]
