# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-27 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0003_auto_20181226_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pic_url',
            field=models.ImageField(max_length=255, upload_to='img'),
        ),
    ]
