# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-03 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0004_auto_20181227_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pic_url',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
